name: CI-CD Pipeline

on:
  pull_request:
    branches: [ "*" ]
  push:
    branches: [ "*" ]

jobs:



  ci:
    name: "ci validate n test"
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' || github.event_name == 'push'

    steps:

      - name: Checkout code
        uses: actions/checkout@v4


      - name: AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-1


      - name: terraform set
        uses: hashicorp/setup-terraform@v2

      - name: terraform lint
        working-directory: Terraform
        run: terraform init -backend=true

      - name: validate
        working-directory: Terraform
        run: terraform validate

    
      - name: docker build backend
        run: docker build -t backend:test backend/

      - name: docker build frontend
        run: docker build -t frontend:test frontend/

    
      - name: Install KubeLinter
        run: |
          curl -L https://github.com/stackrox/kube-linter/releases/latest/download/kube-linter-linux.tar.gz \
          | tar -xz
          sudo mv kube-linter /usr/local/bin/

#      - name: lint check
#       run: kube-linter lint kubernetes/


      - name: artifact
        uses: actions/upload-artifact@v4
        with:
          name: kubernetes-manifests
          path: kubernetes/


  cd:
    name: "cd"
    runs-on: ubuntu-latest
    needs: ci
    if: github.event_name == 'push' || github.event_name == 'push'

    steps:

      - name: Checkout code
        uses: actions/checkout@v4


      - name: AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-1

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }} --region us-east-1
          export KUBECONFIG=$HOME/.kube/config

      - name: Install AWS IAM Authenticator
        run: |
          curl -Lo aws-iam-authenticator https://github.com/kubernetes-sigs/aws-iam-authenticator/releases/latest/download/aws-iam-authenticator_$(uname)_amd64
          chmod +x aws-iam-authenticator
          sudo mv aws-iam-authenticator /usr/local/bin/

      - name: Test Kubernetes access
        run: |
          export KUBECONFIG=$HOME/.kube/config
          aws eks get-token --cluster-name ${{ secrets.EKS_CLUSTER_NAME }} --region us-east-1 > /dev/null
          kubectl get nodes

      - name: terraform
        uses: hashicorp/setup-terraform@v2

      - name: terraform init
        working-directory: Terraform
        run: terraform init

      - name: terraform plan
        working-directory: Terraform
        run: terraform plan

      - name: docker hub login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASS }}

      - name: build and push backend
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USER }}/backend:latest backend/
          docker push ${{ secrets.DOCKERHUB_USER }}/backend:latest

      - name: build and push frontend
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USER }}/frontend:latest frontend/
          docker push ${{ secrets.DOCKERHUB_USER }}/frontend:latest

      - name: Set up AWS CLI EKS authentication
        run: |
         aws eks get-token --cluster-name ${{ secrets.EKS_CLUSTER_NAME }}


      - name: Install NGINX Ingress controller
        run: |
          export KUBECONFIG=$HOME/.kube/config
          helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
          helm repo update
          helm upgrade --install ingress-nginx ingress-nginx/ingress-nginx \
            --namespace ingress-nginx \
            --create-namespace




      - name: Apply kubernetes
        run: kubectl apply -f kubernetes/

    
      - name: verify rollout
        run: |
          kubectl rollout status deployment/backend -n demo-app


      - name: Get Ingress IP
        run: |
          export KUBECONFIG=$HOME/.kube/config
          IP=$(kubectl get svc ingress-nginx-controller -n ingress-nginx --no-headers | awk '{print $4}')
          echo "INGRESS_IP=$IP" >> $GITHUB_ENV


      - name: Smoke test backend API
        run: |
          export KUBECONFIG=$HOME/.kube/config
          sleep 10
          kubectl run curl-pod --image=curlimages/curl -i --rm --restart=Never -- \
          curl http://$INGRESS_IP/backend/health

